### ISSUE TITLE
请问为什么CZ Code.e中的关键字要分为3类存储？

### ISSUE THREAD

**Issue by Henry-ZHR** [chuang-zhi/czcode#3]
RT
这3类有什么区别吗？

**Comment by code004Accepted** [comment]
我认为没有，不过我也不确定qwq

> RT
> 这3类有什么区别吗？

我认为没有，不过我也不确定qwq

@chuang-zhi 您看一下qwq

**Comment by chuang-zhi** [comment]
丢在一起处理时会崩溃

**Comment by Henry-ZHR** [comment]
> 丢在一起处理时会崩溃

那什么条件下不会崩溃呢？

**Comment by chuang-zhi** [comment]
@Henry-ZHR 暂时不能处理，反正没啥子问题，3类是没有区别的
